# Generated by Django 4.1.7 on 2023-03-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sala_de_armas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fusile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('ni', models.IntegerField()),
            ],
        ),
    ]
