# Generated by Django 4.1.7 on 2023-03-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sala_de_armas', '0002_fusile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calibre', models.CharField(max_length=20)),
                ('Cantidad', models.IntegerField()),
            ],
        ),
    ]
