# Generated by Django 4.1.7 on 2023-03-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sala_de_armas', '0003_municion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municion',
            old_name='Calibre',
            new_name='calibre',
        ),
        migrations.RenameField(
            model_name='municion',
            old_name='Cantidad',
            new_name='cantidad',
        ),
    ]
